// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YAOJ.Data;

namespace YAOJ.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180706160844_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("YAOJ.Models.Problem", b =>
                {
                    b.Property<string>("ProblemID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Data");

                    b.Property<string>("DataHash");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Format")
                        .IsRequired();

                    b.Property<string>("Limitation");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Note");

                    b.Property<string>("SampleInput")
                        .IsRequired();

                    b.Property<string>("SampleOutput")
                        .IsRequired();

                    b.HasKey("ProblemID");

                    b.ToTable("Problem");
                });

            modelBuilder.Entity("YAOJ.Models.Record", b =>
                {
                    b.Property<int>("RecordID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("JudgeText");

                    b.Property<string>("Language");

                    b.Property<string>("ProblemID");

                    b.Property<string>("SourceCode");

                    b.Property<int>("Status");

                    b.Property<double>("UsedMemory");

                    b.Property<double>("UsedTime");

                    b.Property<int>("UserID");

                    b.HasKey("RecordID");

                    b.HasIndex("ProblemID");

                    b.HasIndex("UserID");

                    b.ToTable("Record");
                });

            modelBuilder.Entity("YAOJ.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AcceptanceCount");

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("YAOJ.Models.Record", b =>
                {
                    b.HasOne("YAOJ.Models.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemID");

                    b.HasOne("YAOJ.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
